name: Deploy index.html to AWS EC2

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Copy index.html to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOSTS }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "index.html"
        target: "/var/www/html/"
        overwrite: true

    - name: Restart Apache
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOSTS }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo systemctl restart apache2
